name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 29.1
          - 29.2
          - 29.3
          - 29.4
    steps:
      - uses: actions/checkout@v4
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Install prerequisites
        shell: emacs --script {0}
        run: |
          (package-install 'julia-mode t)
          (add-to-list 'load-path "${{ github.workspace }}")
          (require 'julia-ts-mode)
          (treesit-install-language-grammar 'julia)
      - name: MELPA checks
        uses: leotaku/elisp-check@master
        with:
          check: melpa
          file: julia-ts-mode.el
      - name: ERT checks
        uses: leotaku/elisp-check@master
        with:
          check: ert
          file: test/test.el
